export const UPDATE_STATUS_LOADING_PRODUCT = "UPDATE_STATUS_LOADING_PRODUCT";
export const UPDATE_STATUS_LOADING_PRODUCTS = "UPDATE_STATUS_LOADING_PRODUCTS";
export const UPDATE_STATUS_LOADING_PARAMETERS = "UPDATE_STATUS_LOADING_PARAMETERS";
export const UPDATE_STATUS_SAVING_PRODUCT = "UPDATE_STATUS_SAVING_PRODUCT";
export const UPDATE_SEARCH_WORD = "UPDATE_SEARCH_WORD";
