export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCT_BY_ID = "LOAD_PRODUCT_BY_ID";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
