export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
